### ISSUE TITLE
Error when scan the psx rom

### ISSUE THREAD

**Issue by alphatsui** [linuxserver/emulatorjs#70] opened 2022-10-14 16:17 UTC
output:

Scan exited with code: 2

/usr/local/bin/chdman: line 1: unexpected EOF while looking for matching `'' /usr/local/bin/chdman: line 2: syntax error: unexpected end of file

processing Ape Escape (USA).chd

**Comment by LuizMosciaro** [comment] 2022-10-30 15:14
Me too, 

output:

Scan exited with code: 2

/usr/local/bin/chdman: line 1: unexpected EOF while looking for matching `'' /usr/local/bin/chdman: line 2: syntax error: unexpected end of file

processing Castlevania - Symphony of the Night (USA).chd

**Comment by airedwin** [comment] 2022-11-03 04:31
this is because the source they are using for the chdman binary has moved

**Comment by drewschbag** [comment] 2023-02-09 16:09
This isn't an issue with this specific project but with the process of creating a CHD. No dev support needed on this one. 

Start over at the beginning of the conversion process. So if you started with a zip, make sure that zip was complete, extract the bin/cue, then do the chdman step. It should only error out if the image is incomplete at one of these steps. If that's the case, the issue isn't with this project.

**Comment by airedwin** [comment] 2023-02-09 17:38
> This isn't an issue with this specific project but with the process of creating a CHD. No dev support needed on this one.
> 
> Start over at the beginning of the conversion process. So if you started with a zip, make sure that zip was complete, extract the bin/cue, then do the chdman step. It should only error out if the image is incomplete at one of these steps. If that's the case, the issue isn't with this project.

It was but I think it's fixed now, someone updated your link for pulling chdman

**Closed** 2023-06-06 15:36 UTC
Labels: no-issue-activity, closed-issue-activity
